version: 0.1
templates:
- name: yunji_alicloud_ecs_eip
  terraform:
    workdir: ./
    var:
      vswitch_availability_zone: cn-beijing-b
    save_state: true
  description: "\u90E8\u7F72\u963F\u91CC\u4E91ecs+eip\u670D\u52A1"
  timeout: 1500
