version: 0.1
templates:
- name: yunji_alicloud_ecs_eip
  terraform:
    workdir: ./
    var:
      vswitch_availability_zone: "cn-beijing-b"
    save_state: true
    description: "部署阿里云ecs+eip服务"
    timeout: 1500
